### ISSUE TITLE
Common data interface?

### ISSUE THREAD

**Issue by hamelsmu** [kubeflow/code-intelligence#16]
We also may want to develop a common way to fetch data across the projects and perhaps make that into a python library questions to consider:

- Fetching isssues in Bulk (Scraping?)
- Recording Changes to Issues (GitHub App,  subscribes to Issues events and logs those into an event stream of some kind?)
- Fetching notifications in Bulk (Authenticate as a user via Oauth instead of as an app pull previous notifications)
- Fetching new notifications (poll notifications api in allowed interval https://developer.github.com/v3/activity/notifications/)
- etc

Other Technical Questions:
- Way to store json payloads received from subscribing to GitHub Events?  

Thoughts?

_Originally posted by @hamelsmu in https://github.com/kubeflow/code-intelligence/pull/15#issuecomment-513508354_

**Comment by abcdefgs0324** [comment]
I think scrapping the issues is the best way to fetch issues when users install the bot at this moment if API needs to address rate limiting and we can store issue embeddings in feast store.

Do we need to store all json payloads for GitHub Events? Or we address new events using a pipeline and store the needed info into specific storage spaces?

**Comment by hamelsmu** [comment]
> Do we need to store all json payloads for GitHub Events? Or we address new events using a pipeline and store the needed info into specific storage spaces?

Good question.  The data hoarder in me is tempted to say save the json payloads as we may need them down the road for something we haven't thought about to extend the functionality of the bot.  However, at the moment you only need to update the embedding for the Issue in Feast Store (along with a pointer to the original issue, of course)

@jlewi is working on a seperate project to organize/rank notifications.  For notifications, GitHub will not push json payloads.  Instead you have the poll the api periodically to fetch new notifications.  For notifications, I definitely think the raw data should be stored

**Comment by jlewi** [comment]
How does GitHub stale bot work
https://github.com/apps/stale ?

I assume it has a polling based design because it needs to go back and mark issues that have been inactive. So I don't see how it could be responding to a GitHub event saying this issue has been inactive for X days.

I think we can use the API and use a polling based design. We can deliberately spread out our fetching over time based on quota limits.

I think a polling design is easier to provide stability. If our app goes down we can always resume polling from where we left off. However, if we have push based design then if our app goes down recovering is much harder.

**Comment by hamelsmu** [comment]
The code for stale bot is [Open Source](https://github.com/probot/stale).  It appears to poll the data in a smart way based on a delay from when the issue was last touched.

**Comment by hamelsmu** [comment]
closing this issue as I believe it has been resolved
